#!/bin/bash

optionmain=0
until [ "$optionmain" = "4" ]; do
	echo "1) Add Contact"
	echo "2) Modify Contact"
	echo "3) Search Contacts"
	echo "4) Exit"
	
	echo -n "Please enter your choice: "
	read optionmain
	echo ""
	case $optionmain in
		1)
			./addcontacts
		;;
		2)
			./modifycontacts
		;;
		3)
			./searchcontacts
		;;
		4) 	
			echo "Thank you for using our services"
			break
		;;
		*) tput setf 3;echo "Please enter 1, 2, 3, or 4";tput setf 3;
		;;
	esac
done
