#!/bin/bash

option=0
until [ "$option" = "3" ]; do
	echo "1) Search by ID number"
	echo "2) Search by name"
	echo "3) Return"
	
	echo -ne "Please enter your choice: \n"
	read option
	case $option in
		1) 
			echo -e "Pease enter ID number\n"
			read id
			if [[ ${#id} -eq 4 && $id =~ ^[0-9]+$ ]]; then
                                if grep -Fq "Contact ID: $id" contacts; then
               				contact=$(cat contacts | grep -n3 $id | tail -n4)
					echo -e "$contact\n"                 	
				else
                                        echo -e "ERROR: ID could not be found!\n"
                                fi
                        else
                                echo -e "ERROR: Enter correct 4 digit ID number\n!"
                        fi
		;;
		2)
			option2=0
			until [ "$option2" = "4" ]; do
				echo "1) Search by First Name"
				echo "2) Search by Last Name"
				echo "3) Search by part of name"
				echo "4) Return"
				
				echo -ne "Please enter your choice: \n"
				read option2
				case $option2 in
					1)
						echo enter first name
						read fname
						mapfile -t lines < <(cat contacts | grep Full | cut -d: -f2 | sed 's/^ //g' | grep "$fname ")
                                                for name in "${lines[@]}"; do
                                                        printname=$(cat contacts | grep -n3 "$name" | tail -n4)
                                                        echo -e "$printname\n"
                                                done
					;;
					2)
						echo enter last name
						read lname
						mapfile -t lines2 < <(cat contacts | grep Full | cut -d: -f2 | sed 's/^ //g' | grep " $lname")
						for name1 in "${lines2[@]}"; do
							printname2=$(cat contacts | grep -n3 "$name1" | tail -n4)
							echo -e "$printname2\n"
						done
					;;
					3)
						echo enter part of name
						read partname
						mapfile -t lines3 < <(cat contacts | grep Full | cut -d: -f2 | sed 's/^ //g' | grep "$partname")
						for name2 in "${lines3[@]}"; do
        						printname3=$(cat contacts | grep -n3 "$name2" | tail -n4)
        						echo -e "$printname3\n"
						done
					;;
					4) 
						break
					;;
					*) tput setf 3;echo "Please enter 1, 2, 3, or 4";tput setf 3;
				esac	
			done
		;;
		3)
			break
	esac
done
